---
# Moved in to packer script
- name: set timezone to etc/utc
  sudo: yes
  file:
    src: /usr/share/zoneinfo/Etc/UTC
    dest: /etc/localtime
    state: link
    force: yes

# Add hosts to /etc/hosts
- name: configure hosts file
  sudo: yes
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ hostvars[item].ansible_default_ipv4.address }} {{ item }} {{ item }}.novalocal$"
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ item }} {{ item }}.novalocal"
    state: present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: groups['all']

# Moved in to packer script
- name: install httpd-tools
  sudo: yes
  yum:
    name: httpd-tools
    state: present

# Moved in to packer script
- name: disable firewalld
  service: 
    name: firewalld 
    enabled: false 
    state: stopped

- include: users.yml
- include: ssl.yml
